// ─── Dummy Data ───────────────────────────────────────────────────────────────
// All mock data used across the platform. Replace with API calls when backend is ready.

export const DUMMY_VILLAGES = [
  {
    id: 'v1',
    name: 'Rampur Kalan',
    district: 'Meerut',
    state: 'Uttar Pradesh',
    needs: ['Food', 'Medicine', 'Clothing'],
    volunteersAssigned: 4,
    population: 1240,
    status: 'Active',
    urgency: 'High',
    lastUpdated: '2024-03-10',
    description: 'Flood-affected village needing immediate food and medical supplies.',
    image: null,
  },
  {
    id: 'v2',
    name: 'Sitapur Gaon',
    district: 'Muzaffarnagar',
    state: 'Uttar Pradesh',
    needs: ['Education', 'Clothing'],
    volunteersAssigned: 2,
    population: 870,
    status: 'Active',
    urgency: 'Medium',
    lastUpdated: '2024-03-08',
    description: 'Rural village lacking basic educational resources for children.',
    image: null,
  },
  {
    id: 'v3',
    name: 'Devgarh Colony',
    district: 'Hapur',
    state: 'Uttar Pradesh',
    needs: ['Medicine', 'Sanitation'],
    volunteersAssigned: 3,
    population: 560,
    status: 'Pending',
    urgency: 'High',
    lastUpdated: '2024-03-12',
    description: 'Sanitation crisis requiring medical volunteers and hygiene kits.',
    image: null,
  },
  {
    id: 'v4',
    name: 'Bhikampur',
    district: 'Ghaziabad',
    state: 'Uttar Pradesh',
    needs: ['Food', 'Sanitation'],
    volunteersAssigned: 1,
    population: 320,
    status: 'Active',
    urgency: 'Low',
    lastUpdated: '2024-03-05',
    description: 'Small village in recovery phase; needs sustained food distribution.',
    image: null,
  },
  {
    id: 'v5',
    name: 'Nagla Fateh Singh',
    district: 'Meerut',
    state: 'Uttar Pradesh',
    needs: ['Education', 'Food', 'Medicine'],
    volunteersAssigned: 5,
    population: 1890,
    status: 'Active',
    urgency: 'High',
    lastUpdated: '2024-03-13',
    description: 'Large village with multi-dimensional relief needs.',
    image: null,
  },
  {
    id: 'v6',
    name: 'Palri Mafi',
    district: 'Baghpat',
    state: 'Uttar Pradesh',
    needs: ['Clothing'],
    volunteersAssigned: 0,
    population: 210,
    status: 'Pending',
    urgency: 'Low',
    lastUpdated: '2024-03-01',
    description: 'Awaiting first volunteer deployment for clothing distribution.',
    image: null,
  },
];

export const DUMMY_VOLUNTEERS = [
  {
    id: 'vol1',
    name: 'Arjun Mehta',
    email: 'arjun.mehta@email.com',
    skills: ['Medical', 'Logistics'],
    experience: '3 years',
    availability: 'Full-time',
    assignedVillages: ['v1', 'v5'],
    completedTasks: 18,
    rating: 4.9,
    location: 'Meerut, UP',
    priorityScore: 97,
    joinedDate: '2022-01-15',
    status: 'Active',
  },
  {
    id: 'vol2',
    name: 'Priya Sharma',
    email: 'priya.sharma@email.com',
    skills: ['Education', 'Counseling'],
    experience: '2 years',
    availability: 'Weekends',
    assignedVillages: ['v2'],
    completedTasks: 12,
    rating: 4.7,
    location: 'Muzaffarnagar, UP',
    priorityScore: 91,
    joinedDate: '2022-06-20',
    status: 'Active',
  },
  {
    id: 'vol3',
    name: 'Ravi Verma',
    email: 'ravi.verma@email.com',
    skills: ['Logistics', 'Construction'],
    experience: '5 years',
    availability: 'Full-time',
    assignedVillages: ['v3', 'v4'],
    completedTasks: 31,
    rating: 4.8,
    location: 'Ghaziabad, UP',
    priorityScore: 95,
    joinedDate: '2021-09-01',
    status: 'Active',
  },
  {
    id: 'vol4',
    name: 'Sunita Patel',
    email: 'sunita.patel@email.com',
    skills: ['Medical', 'Education'],
    experience: '1 year',
    availability: 'Weekends',
    assignedVillages: ['v1'],
    completedTasks: 6,
    rating: 4.3,
    location: 'Hapur, UP',
    priorityScore: 72,
    joinedDate: '2023-03-10',
    status: 'Active',
  },
  {
    id: 'vol5',
    name: 'Deepak Singh',
    email: 'deepak.singh@email.com',
    skills: ['Logistics', 'Food Distribution'],
    experience: '4 years',
    availability: 'Full-time',
    assignedVillages: ['v5'],
    completedTasks: 24,
    rating: 4.6,
    location: 'Meerut, UP',
    priorityScore: 88,
    joinedDate: '2020-11-22',
    status: 'Active',
  },
  {
    id: 'vol6',
    name: 'Kavita Rao',
    email: 'kavita.rao@email.com',
    skills: ['Counseling', 'Education'],
    experience: '2 years',
    availability: 'Evenings',
    assignedVillages: [],
    completedTasks: 9,
    rating: 4.4,
    location: 'Baghpat, UP',
    priorityScore: 68,
    joinedDate: '2022-12-05',
    status: 'Available',
  },
];

export const DUMMY_TASKS = [
  { id: 't1', title: 'Food distribution — Rampur Kalan', village: 'v1', villageName: 'Rampur Kalan', dueDate: '2024-03-20', status: 'In Progress', priority: 'High', description: 'Distribute 200 food packets to flood-affected families.' },
  { id: 't2', title: 'Medical camp setup — Nagla Fateh Singh', village: 'v5', villageName: 'Nagla Fateh Singh', dueDate: '2024-03-18', status: 'Pending', priority: 'High', description: 'Set up temporary medical camp with doctor visits.' },
  { id: 't3', title: 'Clothing drive — Rampur Kalan', village: 'v1', villageName: 'Rampur Kalan', dueDate: '2024-03-25', status: 'Completed', priority: 'Medium', description: 'Collect and distribute winter clothing to 150 families.' },
  { id: 't4', title: 'Education workshop — Sitapur Gaon', village: 'v2', villageName: 'Sitapur Gaon', dueDate: '2024-03-22', status: 'Pending', priority: 'Medium', description: 'Conduct 2-day literacy workshop for 40 children.' },
];

export const DUMMY_NGO = {
  id: 'ngo1',
  name: 'Aashray Foundation',
  email: 'ngo@aashray.org',
  role: 'ngo',
  registrationNo: 'NGO/UP/2021/00124',
  contact: '+91 9876543210',
  address: 'Meerut, Uttar Pradesh',
  activeVillages: 6,
  totalVolunteers: 6,
  reportsUploaded: 14,
};

export const DUMMY_VOLUNTEER_USER = {
  id: 'vol1',
  name: 'Arjun Mehta',
  email: 'volunteer@email.com',
  role: 'volunteer',
  ...DUMMY_VOLUNTEERS[0],
};
